services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5001:5001"
    depends_on:
      - mongodb
    volumes:
      - ./front-init:/app/front-init
      - ./front-init/storage:/app/front-init/storage

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
